version: '2'
services:
  frontend: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "4200:4200"
    container_name: front-container
    restart: always


  backend: 
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
       - "3000:3000"
    container_name: backend_container
    restart: always
    environment:
      - MONGODB=mongodb+srv://mbenkhal:wE6RSx49o5Acx16x@cluster0-hajpn.mongodb.net/myretail?retryWrites=true

